### PR TITLE
Added blade

### PR DESCRIPTION
**Pull request by concept-core**
Added blade to composer and added custom class.

### CODE REVIEW

**Comment by smolinari** [comment]
Thanks for that. However, this doesn't hook the template system into the framework. I mean, Blade is there, but the framework isn't using it with this PR. Can you figure out how to get the framework to call Blade?

Scott

**Comment by concept-core** [comment]
I can if you can explain me how you call the view.
I am used to call a controller so I only putted it in like this.

Message me om sitepoint.

**Comment by smolinari** [comment]
Currently the View is only a require call to the file system to load a PHP file (aka a "template"). 

https://github.com/SkooppaOS/webMVc/blob/master/src/View.php

This is the trick. We have to figure out how to call the needed templates per object called. The target object is the only stipulation we have in webMVc. For instance, in the clock example, the object is "clock". This must be in the URL as "/clock" to get the clock functions (the pages) to show up.

Scott

**Comment by smolinari** [comment]
Also, the View is simply called from the HTTPConverter. 

https://github.com/SkooppaOS/webMVc/blob/master/src/HTTPConverter.php#L48

Scott

**Comment by smolinari** [comment]
I just breezed over (Blade's code)[https://github.com/PhiloNL/Laravel-Blade/blob/master/src/Blade.php] and I am afraid it isn't going to work stand alone with webMVc, as it requires a ton of classes from Laravel to operate. 

If you are still interested, I'd like to have Twig as the template engine. 

https://github.com/twigphp/Twig

It can definitely run on its own, without Symfony. 

Scott

**Comment by concept-core** [comment]
you know twig also requires tons of code ?
visit this url to check it out how I did it : 
https://ide.c9.io/concept_core/webmvc

**Comment by smolinari** [comment]
I think it will actually be easier to include Twig than Blade, because Twig works standalone, as a component. The issue is, you'll have to have Laravel practically completely installed to run Blade, which makes no sense to me. Might as well use Laravel as your framework then.

Scott

**Comment by concept-core** [comment]
Fine Goodluck with that.
Hope you will get it working.

Best regards,

Wouter van Marrum
Lijsterbesstraat 84
06-39667374
<http://www.concept-core.nl>



Op 20 juli 2015, schreef Scott <notifications@github.com>:

**Pull request closed without merging**
